"""The single table of external tools used by CT Studio.

Only seven documented CLI probes have version_args. GUI and Wine probes stay unset
until P2-T02 verifies safe commands; no GUI is launched just to read its version.
"""

from __future__ import annotations

from types import MappingProxyType

from ctstudio.core.tools.spec import ToolSpec


def _wiimm(tool_id: str, name: str, used_for: str) -> ToolSpec:
    return ToolSpec(
        id=tool_id,
        name=name,
        kind="cli",
        exe_names={"windows": (f"{tool_id}.exe",), "linux": (tool_id,)},
        version_args=("version",),
        version_regex=rf"(?m)^{tool_id}: Wiimms .* v(\d+\.\d+[a-z]?)\b",
        min_version=None,
        homepage="https://szs.wiimm.de/",
        download_page="https://szs.wiimm.de/download/",
        licence="GPL-2.0-or-later (bootstrap catalogue; confirm before redistribution)",
        used_for=used_for,
    )


TOOL_SPECS: tuple[ToolSpec, ...] = (
    _wiimm("wszst", "Wiimms SZS Tool", "SZS assembly, validation and analysis"),
    _wiimm("wkclt", "Wiimms KCL Tool", "Collision analysis and KCL conversion"),
    _wiimm("wkmpt", "Wiimms KMP Tool", "KMP text decoding and encoding"),
    _wiimm("wimgt", "Wiimms Image Tool", "Texture encoding; required by ABMatt"),
    ToolSpec(
        "rszst",
        "RiiStudio CLI",
        "cli",
        {"windows": ("rszst.exe",), "linux": ("rszst",)},
        ("--version",),
        r"(?m)^RiiStudio CLI Alpha (\d+(?:\.\d+)+)\b",
        None,
        "https://github.com/riidefi/RiiStudio",
        "https://github.com/snailspeed3/RiiStudio/releases",
        "Overall licence unconfirmed; do not redistribute",
        "BRRES import and material presets",
    ),
    ToolSpec(
        "abmatt",
        "ABMatt",
        "cli",
        {"windows": ("abmatt.exe",), "linux": ("abmatt",)},
        ("--help",),
        None,
        None,  # Linux v1.3.2 release prints 1.3.1: tag is authority.
        "https://github.com/Robert-N7/abmatt",
        "https://github.com/Robert-N7/abmatt/releases",
        "GPL-3.0",
        "BRRES materials and minimap conversion",
    ),
    ToolSpec(
        "blender",
        "Blender",
        "gui",
        {"windows": ("blender.exe",), "linux": ("blender",)},
        ("--version",),
        r"(?m)^Blender (\d+(?:\.\d+)+)\b",
        None,
        "https://www.blender.org/",
        "https://www.blender.org/download/",
        "GPL-2.0-or-later",
        "Authoring and headless geometry export",
    ),
    ToolSpec(
        "brawlcrate",
        "BrawlCrate",
        "gui",
        {"windows": ("BrawlCrate.exe",), "linux": ("BrawlCrate.exe",)},
        (),
        None,
        None,
        "https://github.com/soopercool101/BrawlCrate",
        "https://github.com/soopercool101/BrawlCrate/releases",
        "See upstream licence; not bundled",
        "Manual BRRES editing",
    ),
    ToolSpec(
        "riistudio",
        "RiiStudio",
        "gui",
        {"windows": ("RiiStudio.exe",), "linux": ("RiiStudio.exe",)},
        (),
        None,
        None,
        "https://github.com/riidefi/RiiStudio",
        "https://github.com/snailspeed3/RiiStudio/releases",
        "Overall licence unconfirmed; do not redistribute",
        "Manual BRRES and post-effect editing",
    ),
    ToolSpec(
        "kmp_editor_lorenzi",
        "Lorenzi's KMP Editor",
        "gui",
        {"windows": ("Lorenzi's KMP Editor.exe",), "linux": ("Lorenzi's KMP Editor.exe",)},
        (),
        None,
        None,
        "https://github.com/hlorenzi/kmp-editor",
        "https://github.com/hlorenzi/kmp-editor/releases",
        "See upstream licence; not bundled",
        "Visual KMP editing (Wine on Linux)",
    ),
    ToolSpec(
        "kmp_cloud",
        "KMP Cloud",
        "gui",
        {"windows": ("KMP Cloud.exe",), "linux": ("KMP Cloud.exe",)},
        (),
        None,
        None,
        "https://mkwiiki.org/wiki/KMP_Cloud",
        "https://mkwiiki.org/wiki/KMP_Cloud",
        "Licence unconfirmed; not bundled",
        "Alternative KMP editing (Wine on Linux)",
    ),
    ToolSpec(
        "dolphin",
        "Dolphin Emulator",
        "gui",
        {"windows": ("Dolphin.exe",), "linux": ("dolphin-emu",)},
        (),
        None,
        None,
        "https://dolphin-emu.org/",
        "https://dolphin-emu.org/download/",
        "GPL-2.0-or-later",
        "Test-launching the custom track",
    ),
    ToolSpec(
        "dolphin_tool",
        "DolphinTool",
        "cli",
        {"windows": ("DolphinTool.exe",), "linux": ("dolphin-tool",)},
        (),
        None,
        None,
        "https://dolphin-emu.org/",
        "https://dolphin-emu.org/download/",
        "GPL-2.0-or-later",
        "Extracting and inspecting a game image",
    ),
    ToolSpec(
        "wine",
        "Wine",
        "cli",
        {"windows": (), "linux": ("wine",)},
        (),
        None,
        None,
        "https://www.winehq.org/",
        "https://wiki.winehq.org/Download",
        "LGPL-2.1-or-later",
        "Running Windows-only editors on Linux",
    ),
    ToolSpec(
        "winetricks",
        "winetricks",
        "cli",
        {"windows": (), "linux": ("winetricks",)},
        (),
        None,
        None,
        "https://github.com/Winetricks/winetricks",
        "https://github.com/Winetricks/winetricks/releases",
        "LGPL-2.1-or-later",
        "Preparing Wine prefixes for editors",
    ),
)

TOOL_BY_ID = MappingProxyType({spec.id: spec for spec in TOOL_SPECS})
